---
kind: pipeline
name: Default

steps:
  - name: Tests
    image: node
    commands:
      - npm ci
      - npm run test

  - name: Generate list
    image: node
    environment:
      TOKEN:
        from_secret: CODEWARS_TOKEN
    commands:
      - npm run build

  - name: Push new list
    image: alpine:latest
    commands:
      - apk add --no-cache openssh-client ca-certificates bash git
      - eval `ssh-agent -s`
      - echo "$KEY" | ssh-add -
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - |-
        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          git add --all
          git commit -m "List :: Updated list [skip ci]"
          git remote set-url origin git@github.com:Alcadramin/codewars.git
          git push -u origin main
        else
          echo "No changes"
          exit 0
        fi
    environment:
      KEY:
        from_secret: GH_SSH_KEY
